CC = c++ -Wall -Wno-parentheses -g
##override CFLAGS += -DHAVE_REMOTE -D_DEBUG
override CFLAGS += -DHAVE_REMOTE
##override CPPFLAGS += -DHAVE_REMOTE -D_DEBUG
override CPPFLAGS += -DHAVE_REMOTE
override LIBS += -lpopt -lpthread -lwpcap
override LDFLAGS += -L/usr/local/lib/x64
